#!/usr/bin/env bash
# Upload all collected (and signed) .deb and .rpm files to a GitHub Release.
# The metadata files (Packages.gz, repomd.xml, etc.) reference these
# URLs, so the Release must exist before users update their package lists.
#
# Env:
#   RELEASE_TAG   tag for this publish run (e.g. "v2026.04.26")
#   GH_REPO       owner/name
#   GITHUB_TOKEN  for `gh release` auth
#   COLLECTED_DIR default: ../collected

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
COLLECTED_DIR="${COLLECTED_DIR:-${REPO_ROOT}/collected}"

: "${RELEASE_TAG:?RELEASE_TAG required}"
: "${GH_REPO:?GH_REPO required}"

# Create the release if it doesn't exist yet
if ! gh release view "${RELEASE_TAG}" --repo "${GH_REPO}" >/dev/null 2>&1; then
    gh release create "${RELEASE_TAG}" \
        --repo "${GH_REPO}" \
        --title "FlagOS packages ${RELEASE_TAG}" \
        --notes "Auto-generated by flagos-packaging publish.yml. Use \`apt install\` or \`dnf install\` (see docs/install.md) — these binaries are referenced by the metadata at https://${GH_REPO%%/*}.github.io/${GH_REPO##*/}/."
fi

# Upload every artifact, --clobber to overwrite if rerunning the same tag
find "${COLLECTED_DIR}" \( -name '*.deb' -o -name '*.rpm' \) -print0 | \
    xargs -0 -r gh release upload "${RELEASE_TAG}" --repo "${GH_REPO}" --clobber

echo "uploaded artifacts to release ${RELEASE_TAG}"
